In [16]:
import pandas as pd

df = pd.read_csv("cleaned_dataset.csv")
df.head()

,product_id,title,condition,resale_price,location
0,L0283,Lenovo Ideapad 320-15IKBN 6GB Used good condition,Used,289.50,Chennai
1,L0410,Lenovo ThinkPad P51 8GB Used good condition,Used,962.50,Bangalore
2,L0583,Dell Latitude 5580 16GB Like New good condition,Like New,1229.91,Bangalore
3,L0407,Dell Latitude 7480 8GB Like New good condition,Like New,1344.00,Bangalore
4,L0509,Lenovo Legion Y520-15IKBN 8GB Like New good co...,Like New,919.20,Bangalore

In [17]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.info()

Rows: 200
Columns: 5
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    200 non-null    object
 1   title         200 non-null    object
 2   condition     200 non-null    object
 3   resale_price  200 non-null    float64
 4   location      200 non-null    object
dtypes: float64(1), object(4)
memory usage: 7.9+ KB

In [18]:
df.describe(include="all")

,product_id,title,condition,resale_price,location
count,200,200,200,200.000000,200
unique,200,188,3,NaN,4
top,L0283,HP ProBook 450 4GB Used good condition,Used,NaN,Mumbai
freq,1,3,76,NaN,56
mean,NaN,NaN,NaN,714.101250,NaN
std,NaN,NaN,NaN,458.694386,NaN
min,NaN,NaN,NaN,101.450000,NaN
25%,NaN,NaN,NaN,364.800000,NaN
50%,NaN,NaN,NaN,625.200000,NaN
75%,NaN,NaN,NaN,951.900000,NaN
max,NaN,NaN,NaN,2449.500000,NaN

In [19]:
df.isnull().sum()

product_id      0
title           0
condition       0
resale_price    0
location        0
dtype: int64

In [20]:
df["condition"].value_counts()

condition
Used           76
Like New       66
Refurbished    58
Name: count, dtype: int64

In [21]:
df["location"].value_counts()

location
Mumbai       56
Hyderabad    54
Bangalore    48
Chennai      42
Name: count, dtype: int64

In [22]:
df["resale_price"].describe()

count     200.000000
mean      714.101250
std       458.694386
min       101.450000
25%       364.800000
50%       625.200000
75%       951.900000
max      2449.500000
Name: resale_price, dtype: float64

=========================================        END        ==================================================