In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("feature_engineered_dataset.csv")
df

,product_id,title,condition,resale_price,location,title_word_count,title_length,price_category
0,L0283,Lenovo Ideapad 320-15IKBN 6GB Used good condition,Used,289.50,Chennai,7,49,Low
1,L0410,Lenovo ThinkPad P51 8GB Used good condition,Used,962.50,Bangalore,7,43,Medium
2,L0583,Dell Latitude 5580 16GB Like New good condition,Like New,1229.91,Bangalore,8,47,Medium
3,L0407,Dell Latitude 7480 8GB Like New good condition,Like New,1344.00,Bangalore,8,46,Medium
4,L0509,Lenovo Legion Y520-15IKBN 8GB Like New good co...,Like New,919.20,Bangalore,8,53,Medium
...,...,...,...,...,...,...,...,...
195,L0610,Lenovo Thinkpad P51 32GB Used good condition,Used,2449.50,Mumbai,7,44,High
196,L0580,Mediacom SmartBook Edge 4GB Like New good cond...,Like New,311.20,Mumbai,8,51,Low
197,L0306,HP EliteBook x360 16GB Like New good condition,Like New,1580.00,Mumbai,8,46,Medium
198,L0048,Dell Inspiron 3567 4GB Refurbished good condition,Refurbished,415.35,Bangalore,7,49,Low
199,L0012,Apple MacBook Pro 16GB Refurbished good condition,Refurbished,1585.98,Bangalore,7,49,Medium

Highest average resale price

In [4]:
df.groupby("location")["resale_price"].mean().sort_values(ascending=False)

location
Mumbai       813.862679
Chennai      724.979048
Hyderabad    661.935556
Bangalore    646.881250
Name: resale_price, dtype: float64

Highest selling condition

In [5]:
df.groupby("condition")["resale_price"].mean()

condition
Like New       916.340455
Refurbished    670.095172
Used           572.056053
Name: resale_price, dtype: float64

Top expensive listings

In [6]:
df.sort_values("resale_price",ascending=False).head(10)

,product_id,title,condition,resale_price,location,title_word_count,title_length,price_category
195,L0610,Lenovo Thinkpad P51 32GB Used good condition,Used,2449.50,Mumbai,7,44,High
147,L0650,Asus ROG G701VI 32GB Like New good condition,Like New,2239.20,Chennai,8,44,High
148,L0003,Apple MacBook Pro 16GB Like New good condition,Like New,2029.96,Mumbai,8,46,High
191,L0204,Dell Precision 7520 16GB Refurbished good cond...,Refurbished,1985.75,Mumbai,7,51,High
57,L0642,Lenovo ThinkPad X1 16GB Like New good condition,Like New,1960.00,Hyderabad,8,47,High
53,L0835,Dell Alienware 15 16GB Refurbished good condition,Refurbished,1803.51,Mumbai,7,49,High
5,L0905,LG Gram 15Z970 16GB Like New good condition,Like New,1679.20,Chennai,8,43,High
97,L0312,MSI GE63VR 7RF 16GB Like New good condition,Like New,1679.20,Hyderabad,8,43,High
125,L0433,Lenovo Thinkpad T570 16GB Refurbished good con...,Refurbished,1589.25,Hyderabad,7,52,Medium
199,L0012,Apple MacBook Pro 16GB Refurbished good condition,Refurbished,1585.98,Bangalore,7,49,Medium

Most common condition

In [7]:
df["condition"].mode()

0    Used
Name: condition, dtype: object

=====================================================    END    ==============================================